name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: |
        ${{ github.action_path }}/goodbye.sh
        export VM_NAME=$RANDOM
        echo "::set-output name=random-id::$(echo $VM_NAME)"
        python3 ${{ github.action_path }}/main.py
      shell: bash
