name: 'orka-actions-up'
description: 'spin up an orka actions runner'
outputs:
  vm-name:
    description: "VM name"
    value: ${{ steps.runner-up.outputs.vm-name }}
runs:
  using: "composite"
  steps:
    - id: runner-up
      run: |
        ${{ github.action_path }}/run.sh
        export VM_NAME=$(cat /dev/urandom | tr -dc '[:alpha:]' | fold -w ${1:-20} | head -n 1)
        echo "::set-output name=vm-name::$(echo $VM_NAME)"
        python3 ${{ github.action_path }}/main.py
      shell: bash
