on:
  push:
    branches:
      - test

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - id: foo
      - run: echo $RANDOM
        shell: bash
  job2:
    needs: job1
    runs-on: ubuntu-latest
    name: job2
    steps:
      - id: bar
      - run: echo $RANDOM
        shell: bash
      
